method: sconet
data:
  dataset: AbdomenCT-1K
  dataset_type: Shapes3D
  data_path: data/ShapeNet
  mapping_file: null
  input_type: pointcloud
  random_linear_transform: 0.1
  train_split: train
  val_split: val
  test_split: test
  dim: 3
  points_file: points.npz
  points_metric_file: points.npz
  points_subsample: 1024
  points_subsample_validation: 524288
  points_subsample_validation_seed: 100
  pointcloud_file: pointcloud.npz
  pointcloud_n: 256
  padding: 0.1
  # Preprocessing parameters
  int8 : true
  surf_extras: -bin 1 -csvgz 0 -s 0.75 -pad 30 -normalize 0 -cmin -100 -cmax 512
  mri: false
  to_RAS: false
  canny_path: ''
  canny_resolution: -1
  canny_threshold:
    low: 20
    up: 50
  canny_variance: 2
model:
  decoder: simple
  encoder: resnet18
  decoder_kwargs: {}
  encoder_kwargs: {}
  multi_gpu: false
  c_dim: 512
training:
  out_dir:  out/default
  batch_size: 1
  compute_metric_on_training_set : False
  model_selection_metric: loss
  model_selection_mode: minimize
  n_workers: 8
  n_workers_val: 8
  loss: DiceLoss
  loss_parameters:
    alpha : 1
    beta : 1
  n_epoch: 300
  learning_rate: 0.0001
  optimizer: Adam
  momentum: 0.90
  seed: 666
  weight_decay: 0.0
  pre_trained_model_file: none 
generation:
  threshold: 0.5
  model_file: model_best.pt
  generation_seed: 10
  batch_size: 1
  generation_dir: generation
  copy_input: false
  compute_flops: false
  compute_volume: true
  low_res: true
